apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-backend.fullname" . }}
  labels:
    {{- include "api-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-backend.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      dnsPolicy: None  # Désactive la politique DNS par défaut
      dnsConfig:
        nameservers:
          - 8.8.8.8  # Utilise les serveurs DNS de Google
        searches:
          - default.svc.cluster.local
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api-backend.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      #initContainers:
      #  - name: pozos-initialization
      #   image: curlimages/curl
      #    env:
      #    - name: LIST_URL
      #      value: {{ .Values.listUrl }}
      #    command: ['sh', '-c', "curl $LIST_URL -o /data/student_age.json"]
      #    volumeMounts:
      #   - name: student-list
      #     mountPath: /data      
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: api-backend 
              containerPort: {{ .Values.service.targetPort }} 
              protocol: TCP   
        #  volumeMounts:
        #  - name: student-list
        #    mountPath: /data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}              
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: student-list 
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "api-backend.fullname" .}}
          {{- else }}
          emptyDir: {}
          {{ end }}   
